---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.issuerName }}
spec:
  acme:
       # The ACME server URL
    server: {{ .Values.server }}
       # Email address used for ACME registration
    email: {{ .Values.email }}
     # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: {{ .Values.issuerSecret }}
      # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            class: treafik
            