NAME: zapisywarka
LAST DEPLOYED: Sun Dec 18 21:51:36 2022
NAMESPACE: default
STATUS: pending-install
REVISION: 1
TEST SUITE: None
HOOKS:
MANIFEST:
---
# Source: zapisywarka/charts/api/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: zapisywarka-api
  labels:
    helm.sh/chart: api-0.1.0
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: zapisywarka
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: zapisywarka
---
# Source: zapisywarka/charts/api/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zapisywarka-api
  labels:
    helm.sh/chart: api-0.1.0
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: zapisywarka
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api
      app.kubernetes.io/instance: zapisywarka
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
        app.kubernetes.io/instance: zapisywarka
    spec:
      serviceAccountName: default
      securityContext:
        {}
      containers:
        - name: api
          securityContext:
            {}
          image: "ghcr.io/zapisywarka-api:cdfe08751ce8"
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRESQL__DB
              valueFrom:
                secretKeyRef:
                  key: dbname
                  name: zapisywarka-dbuser
            - name: POSTGRESQL__HOST
              valueFrom:
                secretKeyRef:
                  key: host
                  name: zapisywarka-dbuser
            - name: POSTGRESQL__USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: zapisywarka-dbuser
            - name: POSTGRESQL__PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: zapisywarka-dbuser
            - name: DOMAIN
              value: zapisywarka.local
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
---
# Source: zapisywarka/charts/api/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zapisywarka-api
  labels:
    helm.sh/chart: api-0.1.0
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: zapisywarka
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  rules:
    - host: zapisywarka.local
      http:
        paths:         
          - path: /
            pathType: ImplementationSpecific           
            backend:
              service:
                name: zapisywarka-api
                port:
                  number: 80

