version: '3.4'

services:


  web: 
    container_name: zapisywarka_web
    image: ghcr.io/msz13/zapisywarka_web:latest
    build: 
        context: .
        dockerfile: ./Deployment/nginx/Dockerfile
    ports:
    - 80:80

  


  web-api:
    container_name: zapisywarka_api
    image: ghcr.io/msz13/zapisywarka_api:latest
    build:
      context: .
      dockerfile: ./src/Zapisywarka.API/DockerFile
    environment:
      ConnectionStrings__Postgresql: "Host=postgres;Database=Offers;Username=postgres;Password=Password_01"
  

  postgres:
    container_name: postgres_container2
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password_01
      POSTGRES_DB: Zapisywarka
    volumes:
       - D:\programowanie\kooperatywy\postgresql\data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    restart: unless-stopped
  
  pgAdmin:
    restart: always
    image: dpage/pgadmin4
    ports:
       - "8001:80"
    environment:
       PGADMIN_DEFAULT_EMAIL: 1234@admin.com
       PGADMIN_DEFAULT_PASSWORD: 1234
      