apiVersion: v1
data:
  config.json: "{ \n    \"identityServer\": \"api.zapisywarka.local\",\n    \"clientId\":
    \"spa\" \n}\n    \n"
kind: ConfigMap
metadata:
  labels:
    app: rejestracja
    env: staging
  name: dev-zapisywarka-web-configuration-d6c54965mf
---
apiVersion: v1
data:
  .dockerconfigjson: |
    ewogICAgImF1dGhzIjoKICAgIHsKICAgICAgICAiZ2hjci5pbyI6CiAgICAgICAgICAgIH
    sKICAgICAgICAgICAgICAgICJhdXRoIjoiYlhONk1UTTZaMmh3WDBOdFJ6QndSRkJSY1Vk
    UE1YWjNRVEZ1UVZWbVVYbDJXV1pOYWtsVE1URlNaM2x3VFFvPSIKICAgICAgICAgICAgfQ
    ogICAgfQp9Cg==
kind: Secret
metadata:
  labels:
    app: rejestracja
    env: staging
  name: regcred-tc7t5kck58
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rejestracja
    env: staging
  name: dev-zapisywarka-web
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: rejestracja
    env: staging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rejestracja
    env: staging
  name: dev-zapisywarka-web
spec:
  selector:
    matchLabels:
      app: rejestracja
      env: staging
  template:
    metadata:
      labels:
        app: rejestracja
        env: staging
    spec:
      containers:
      - image: ghcr.io/msz13/zapisywarka-rejestracja:0a0e4eb16b9f9012e3f6339fc3dd02f7e5973243
        imagePullPolicy: IfNotPresent
        name: web
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html/assets/
          name: config-volume
      imagePullSecrets:
      - name: regcred-tc7t5kck58
      volumes:
      - configMap:
          name: dev-zapisywarka-web-configuration-d6c54965mf
        name: config-volume
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: rejestracja
    env: staging
  name: dev-zapisywarka-web
spec:
  rules:
  - host: 193.123.39.204.nip.io
    http:
      paths:
      - backend:
          service:
            name: dev-zapisywarka-web
            port:
              number: 80
        path: /
        pathType: Prefix
