apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
   - https://raw.githubusercontent.com/kubernetes/dashboard/v2.2.0/aio/deploy/recommended.yaml
   - https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.4.2/components.yaml
   - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.48.1/deploy/static/provider/cloud/deploy.yaml

patchesStrategicMerge:
  - metrics-server-patch.yml