apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: API
  template:
    metadata:
      labels:
        app: API
    spec:
      containers:
      - name: api
        image: zapisywarka-api:test        
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:          
          - name: POSTGRESQL__DB
            valueFrom: { secretKeyRef: { name: zapisywarka-db-dbuser, key: dbname } }
          - name: POSTGRESQL__HOST
            valueFrom: { secretKeyRef: { name: zapisywarka-db-dbuser, key: host } }
          - name: POSTGRESQL__USER
            valueFrom: { secretKeyRef: { name: zapisywarka-db-dbuser, key: user } }                
          - name: POSTGRESQL__PASSWORD
            valueFrom: { secretKeyRef: { name: zapisywarka-db-dbuser, key: password } } 
          - name: POSTGRESQL__URI
            valueFrom: { secretKeyRef: { name: zapisywarka-db-dbuser, key: uri } } 
          - name: DOMAIN
            value: zapisywarka.local

