namePrefix: zapisywarka-

commonLabels:
  app: zapisywarkaApi

#patchesStrategicMerge:
#- init-container.yml

#- postgresql-db.yml
resources:
- deployment.yml
- service.yml
- api-ingress.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
