apiVersion: v1
kind: Secret
data:  
  dbname: emFwaXN5d2Fya2EK
  host: emFwaXN5d2Fya2EtZGIK
  port: NTQzMgo=
  user: ZGJvd25lcgo=
  password: WkRKbU1tRTJNemMzWmpKallUSTRaVGswTURjNE9XVTQK
  create-user.sql: Y3JlYXRlIHVzZXIgZGJvd25lciBwYXNzd29yZCAnWkRKbU1tRTJNemMzWmpKallUSTRaVGswTURjNE9XVTQnOwpHUkFOVCBwZ19kYXRhYmFzZV9vd25lciBUTyBkYm93bmVyOwo=
metadata:  
  name: zapisywarka-db-dbowner  
type: Opaque
