---
# Source: stackgres-cluster/templates/SGScript.yml
apiVersion: v1
data: 
  dbname: emFwaXN5d2Fya2ExNA==
  host: dGVzdC1kYg==
  port: IjU0MzIi
  user: ZGJ1c2Vy
  password: lnP9c84R2VHcDDOYKvKu
  create-user.sql: |
    CmNyZWF0ZSB1c2VyIGRidXNlciBwYXNzd29yZCBsblA5Yzg0UjJWSGNERE9ZS3ZLdTsK
kind: Secret
metadata:  
  name: zapisywarka14-dbuser  
type: Opaque
---
# Source: stackgres-cluster/templates/SGScript.yml
apiVersion: v1
data: 
  dbname: emFwaXN5d2Fya2ExNA==
  host: dGVzdC1kYg==
  port: IjU0MzIi
  user: ZGJvd25lcg==
  password: FtOCx0CsqLP9qc0dH74C
  create-user.sql: |
    CmNyZWF0ZSB1c2VyIGRib3duZXIgcGFzc3dvcmQgRnRPQ3gwQ3NxTFA5cWMwZEg3NEM7Cg==
kind: Secret
metadata:  
  name: zapisywarka14-dbowner  
type: Opaque
---
# Source: stackgres-cluster/templates/SGScript.yml
apiVersion: stackgres.io/v1beta1
kind: SGScript
metadata:
  name: script
spec:
  managedVersions: true
  continueOnError: false
  scripts:
  - name: create-user-dbowner
    scriptFrom:
      secretKeyRef: # read the user from a Secret to maintain credentials in a safe place
        name: zapisywarka14-dbowner
        key: create-user.sql
  - name: create-user-dbuser
    scriptFrom:
      secretKeyRef: # read the user from a Secret to maintain credentials in a safe place
        name: zapisywarka14-dbuser
        key: create-user.sql
  - name: create-stackgres-database
    script: |
      CREATE DATABASE zapisywarka14;
  - name: grant-roles-to-users
    database: zapisywarka14
    script: |
      GRANT pg_read_all_data TO dbuser;
      GRANT pg_write_all_data TO dbuser;
