apiVersion: v1
data:  
  dbname: emFwaXN5d2Fya2EK
  host: emFwaXN5d2Fya2EtZGIK
  port: NTQzMgo=
  user: ZGJvd25lcgo=
  password: WkRKbU1tRTJNemMzWmpKallUSTRaVGswTURjNE9XVTQK
kind: Secret
metadata:  
  name: zapisywarka-db-dbowner  
type: Opaque
