apiVersion: v1
data:  
  dbname: emFwaXN5d2Fya2EK
  host: emFwaXN5d2Fya2EtZGIK
  port: NTQzMgo=
  user: ZGJ1c2VyCg==
  password: WVRObE16Tm1NalZtTVRNME1XVm1PRFZsTmpobVltVTMK
kind: Secret
metadata:  
  name: zapisywarka-db-dbuser  
type: Opaque
