apiVersion: stackgres.io/v1
kind: SGCluster
metadata:
  name: zapisywarka-db
spec:
  instances: 1
  postgres:
    version: 'latest'
  pods:
    persistentVolume:
      size: '1Gi'  
  managedSql:
    scripts:
      - sgScript: zapisywarka-scripts
  


