name: 'Setup docker environment'
inputs:
  username:  # id of input
    description: docker registry username
    required: true    
  password: 
    description: docker registry password
    required: false
  
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2        
    - name: Docker Login  
      run:  echo "${{ inputs.password }}" | docker login ghcr.io -u ${{ inputs.username }} --password-stdin 
      shell: bash
     

