apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: stack-gres
  namespace: stackgres
spec:  
  chart: https://stackgres.io/downloads/stackgres-k8s/stackgres/latest/helm/stackgres-operator.tgz
  targetNamespace: stackgres
  set:
    adminui:
      service:
        type: NodePort
        nodePort: 9000
  