apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: API
  template:
    metadata:
      labels:
        app: API
    spec:
      containers:
      - name: api
        image: k3d-zapisywarka.localhost:9009/zapisywarka-api:latest
        imagePullPolicy: Always        
        ports:
        - containerPort: 5000
        env:          
          - name: POSTGRESQL__DB
            value: zapisywarka-db
          - name: POSTGRESQL__HOST
            value: zapisywarka-postgres
          - name: POSTGRESQL__USER
            valueFrom:
              secretKeyRef:
                name: zapisywarka-api.zapisywarka-postgres.credentials
                key: username                
          - name: POSTGRESQL__PASSWORD
            valueFrom:  
              secretKeyRef:
                name: zapisywarka-api.zapisywarka-postgres.credentials
                key: password

