version: '3.9'

services:
  postgres:
    container_name: postgres_container_test
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password_01
      POSTGRES_DB: zapisywarka
    #volumes:
    #   - D:\programowanie\kooperatywy\postgresql\data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    restart: unless-stopped
  pgAdmin:
        restart: always
        image: dpage/pgadmin4
        ports:
            - "8000:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: 1234@admin.com
            PGADMIN_DEFAULT_PASSWORD: 1234
      
  
