apiVersion: k3d.io/v1alpha2
kind: Simple
name: zapisywarka-local
ports:
- port:  80:80
  nodeFilters:
    - loadbalancer
image: rancher/k3s:v1.21.2-k3s1
volumes:
  - volume:  /home/msz13/programowanie/zapisywarka/Deployment/dev-cluster-infrastructure/postgres-operator.yml:/var/lib/rancher/k3s/server/manifests/postgres-operator.yml
registries: 
  enable: false

