apiVersion: v1
data:
  .dockerconfigjson: |
    ewogICAgImF1dGhzIjoKICAgIHsKICAgICAgICAiZ2hjci5pbyI6CiAgICAgICAgICAgIH
    sKICAgICAgICAgICAgICAgICJhdXRoIjoiYlhONk1UTTZaMmh3WDJodU1FaDNOMmhXYkZk
    T01XTldkMHRoTlhKblJYazNOR0pKYUVOMU5URlhTRWhPVXdvPSIKICAgICAgICAgICAgfQ
    ogICAgfQp9Cg==
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson