export const CATALOG_ITEM = {
  id: 1,
  name: 'Bochenek tradycyjny',
  categoryId: 1,
  price: 9,
  avaibleQuantity: 60,
};

export const CATALOG_ITEMS = [
  {
    id: 1,
    name: 'Bochenek tradycyjny',
    categoryId: 1,
    price: 9,
    avaibleQuantity: 60,
  },
  {
    id: 2,
    name: 'Bochenek francuski',
    categoryId: 1,
    price: 9,
    avaibleQuantity: 60,
  },
  {
    id: 3,
    name: 'Bochenek wiejski',
    categoryId: 1,
    price: 9,
    avaibleQuantity: 60,
  },
  {
    id: 4,
    name: 'Bochenek z szuszonymi pomidorami',
    categoryId: 1,
    price: 9,
    avaibleQuantity: 60,
  },
  {
    id: 5,
    name: 'Foremkowy',
    categoryId: 2,
    price: 6,
    avaibleQuantity: 40,
  },
  {
    id: 6,
    name: 'Foremkowy z żurawiną',
    categoryId: 2,
    price: 6,
    avaibleQuantity: 40,
  },
  {
    id: 7,
    name: 'Foremkowy z ziarnami',
    categoryId: 2,
    price: 6,
    avaibleQuantity: 40,
  },
  {
    id: 8,
    name: 'Foremkowy z morelami i rozmarynem',
    categoryId: 2,
    price: 6,
    avaibleQuantity: 40,
  },
  {
    id: 9,
    name: 'Foremkowy z czarnuszką',
    categoryId: 2,
    price: 6,
    avaibleQuantity: 40,
  },
  {
    id: 10,
    name: 'Orkiszowy',
    categoryId: 3,
    price: 11,
    avaibleQuantity: 40,
  },
  {
    id: 11,
    name: 'Bułeczki ciabatta',
    categoryId: 3,
    price: 11,
    avaibleQuantity: 40,
  },
  {
    id: 12,
    name: 'Bochenek "dysk"',
    categoryId: 1,
    price: 9,
    avaibleQuantity: 60,
  },
];
