# Default values for zapisywarka-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

aspnet-core:
  enable: true
  image:
    repository: zapisywarka-api
    tag: cdfe08751ce8

  command: ["dotnet", "./net6.0/ZapisywarkaClientAps.ZapisywarkaApi.dll"]

  ingress:
    enabled: true
    hostname: api.zapisywarka.local

  extraEnvVars: 
    - name: POSTGRESQL__DB
      valueFrom: { secretKeyRef: { name: zapisywarka14-dbuser, key: dbname } }
    - name: POSTGRESQL__HOST
      valueFrom: { secretKeyRef: { name: zapisywarka14-dbuser, key: host } }
    - name: POSTGRESQL__USER
      valueFrom: { secretKeyRef: { name: zapisywarka14-dbuser, key: user } }                
    - name: POSTGRESQL__PASSWORD
      valueFrom: { secretKeyRef: { name: zapisywarka14-dbuser, key: password } } 
    - name: DOMAIN
      value: zapisywarka.local

  appFromExternalRepo:
    enabled: false
  serviceAccount: 
    create: false