# Default values for zapisywarka.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  imageRegistry: ghcr.io


api:  
  image:
    repository: zapisywarka-api
    tag: cdfe08751ce8
  ingress:
    hostname: zapisywarka.local  
  env:
    - name: POSTGRESQL__DB
      valueFrom: { secretKeyRef: { name: zapisywarka-dbuser, key: dbname } }
    - name: POSTGRESQL__HOST
      valueFrom: { secretKeyRef: { name: zapisywarka-dbuser, key: host } }
    - name: POSTGRESQL__USER
      valueFrom: { secretKeyRef: { name: zapisywarka-dbuser, key: user } }                
    - name: POSTGRESQL__PASSWORD
      valueFrom: { secretKeyRef: { name: zapisywarka-dbuser, key: password } } 
    - name: DOMAIN
      value: zapisywarka.local