# Default values for zapisywarka.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  imageRegistry: ""
  imagePullSecrets: []
    


api:  
  image:
    repository: zapisywarka-api
    tag: cdfe08751ce8
  service:
    port: 5000
  ingress:
    hostname: api.zapisywarka.local      
  env:
    - name: POSTGRESQL__DB
      valueFrom: { secretKeyRef: { name: zapisywarka-dbuser, key: dbname } }
    - name: POSTGRESQL__HOST
      valueFrom: { secretKeyRef: { name: zapisywarka-dbuser, key: host } }
    - name: POSTGRESQL__USER
      valueFrom: { secretKeyRef: { name: zapisywarka-dbuser, key: user } }                
    - name: POSTGRESQL__PASSWORD
      valueFrom: { secretKeyRef: { name: zapisywarka-dbuser, key: password } } 
    - name: DOMAIN
      value: zapisywarka.local

  
rejestracja:
  image:  
    repository: zapisywarka-rejestracja
    tag: e29eecf4f547
  ingress: 
    hostname: zapisywarka.local      
  configFile:
    name: config.json
    path: /usr/share/nginx/html/assets/    
    content: |
      { 
        "apiUrl": "http://api.zapisywarka.local"       
      }

postgres-cluster:
  storageSize: 1Gi
  database:
    enable: true
    name: zapisywarka
    owner: dbowner
    users:   
      - name: dbuser
        roles: [ pg_read_all_data, pg_write_all_data ]

db-migrations:
  image: 
    repository: db-migrations
    tag: 0.1.0
#  command: ["/usr/bin/dotnet", "/publish/ZapisywarkaClientAps.DbMigrations.dll"]    
  env:
    - name: DB_NAME
      valueFrom: { secretKeyRef: { name: zapisywarka-dbowner, key: dbname } }
    - name: DB_HOST
      valueFrom: { secretKeyRef: { name: zapisywarka-dbowner, key: host } }
    - name: DB_PORT
      valueFrom: { secretKeyRef: { name: zapisywarka-dbowner, key: port } }           
    - name: DB_USER
      valueFrom: { secretKeyRef: { name: zapisywarka-dbowner, key: user } }
    - name: DB_PASSWORD
      valueFrom: { secretKeyRef: { name: zapisywarka-dbowner, key: password } }
  helmHook: post-install, pre-upgrade
  backoffLimit: 10
  ttlSecondsAfterFinished: 60



    



