namePrefix: dev-zapisywarka-

commonLabels:
  app: zapisywarka-web

configMapGenerator:
- files:
  - config.json
  name: web-configuration

resources:
- deployment.yml
- service.yml
- ingress.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: zapisywarka-rejestracja
  newName: k3d-zapisywarka.localhost:9009/zapisywarka-rejestracja
  newTag: c10eabca34f1
