namePrefix: zapisywarka-

commonLabels:
  app: zapisywarkaApi

patchesStrategicMerge:
- init-container.yml

resources:
- postgresql-db.yml
- deployment.yml
- service.yml
- api-ingress.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: zapisywarka-api
  newName: k3d-zapisywarka.localhost:9009/zapisywarka-api
  newTag: dca5554daddd
