apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: zapisywarka-postgres
  namespace: default
spec:
  teamId: zapisywarka
  volume:
    size: 1Gi
    #storageClass: local-path
  numberOfInstances: 1
  users:
    zapisywarka-api:  # database owner
    - superuser
    - createdb
  databases:
    zapisywarka-db: zapisywarka-api  # dbname: owner  
  postgresql:
    version: "13"