openapi: '3.0.2'
info:
  title: Zapisywarka
  version: '1.0'
servers:
  - url: https://api.zapisywarka.pl
  - url: https://test.api.zapisywarka.pl
paths: 
  /users:
    post:
      summary: Creates new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                accessCode:
                  type: string
                userName:
                  type: string
                  minLength: 3
                  maxLength: 32
                password:
                  type: string
                  minLength: 8
                  format: password                  
      responses:
        '201':
          description: OK
    get:
      summary: Gets all users
      responses:
        '200':
          description: Returns all users
          content:
           application/json:
             schema:
              type: array
              items: 
                  $ref: '#/components/schemas/UserInfo'            
  /users/login:
    post:
      summary: Login user
      requestBody:        
        content: 
          application/json:
            schema:
              type: object
              properties:
                userName: 
                  type: string
                password: 
                  type: string
                rememberMe: 
                  type: boolean
              required:
                - userName
                - password          
      responses:
        '200':
          description: OK 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'         
        '400':
          description: Missing values
          content:
            application/json:
              schema:
               $ref: '#/components/schemas/Error'
        '401':
          description: Invalid username or password 
          content:
            application/json:
              schema:
               $ref: '#/components/schemas/Error'   
  /users/me:
    get:
      summary: Get user claim of logged in user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
        '401':
          description: Anauthycated user 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
  /offers/{offerId}:
    get:
      description: 'get offer by id'
      parameters: 
        - name: offerId
          in: path
          schema: 
            type: string
          required: true
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OfferForm'
        '404':
          description: offer id not exists
          content:
            application/json:
              schema:
               $ref: '#/components/schemas/Error'
  /offers/{offerId}/registration:
    post:
      description: 'register reserveation'
      parameters: 
        - name: offerId
          in: path
          schema: 
            type: string
          required: true
      requestBody:
        content: 
          application/json:
            schema:
              type: object
              properties:                
                receptionPassword:
                  type: string
                comments:
                  type: string
                reservedItems:
                  type: array
                  minItems: 1
                  uniqueItems: true
                  items: 
                    $ref: '#/components/schemas/reservedItem'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegistrationDetails'
        '400':
          description: Bad input
          content:
            application/json:
              schema:
               $ref: '#/components/schemas/Error'
        '422':
          description: domain errors
          content:
            application/json:
              schema:
               $ref: '#/components/schemas/Error'
          
components:
  schemas:
    Error: 
      type: object
      properties:
        message:
          type: string
    UserInfo:
      type: object
      properties:
        id:
          type: string
        userName:
          type: string
      required:
        - id
        - username
    OfferForm:
      type: object
      properties:
        offerId: 
          type: string
        name: 
          type: string
        offerItems:
          type: array
          items:
            $ref: '#/components/schemas/OfferItems'
    OfferItems:
      type: object
      properties:
        offerItemId:
          type: string
        name: 
          type: string
        price:
          type: number
    reservedItem:
      type: object
      properties:
        reservedItemId:
          type: integer
        offerItemId:
          type: string
        quantity:
          type: integer
    RegistrationDetails:
      type: object
      properties:
          id: 
            type: string
          reservationNumber:
            type: string
          totalCost:
            type: number
          offerId: 
            type: string
          receptionPassword:
             type: string
          comments: 
            type: string
          offerItems:
             type: array
             items: 
               $ref: '#/components/schemas/RegistrationDetailsItem'
    RegistrationDetailsItem: 
      type: object
      properties:
        offerItemId:
          type: string
        quantity:
          type: integer
        cost: 
          type: number
     

    
