apiVersion: skaffold/v2beta22
kind: Config
metadata:
  name: zapisywarka
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: zapisywarka-web
      custom:
        buildCommand: ./build-image.sh

  local: {}

deploy:
  kustomize:
    paths:
      - deployment
