loki:
  enabled: true

promtail:
  enabled: true

grafana:
  enabled: true
  sidecar:
    datasources:
      enabled: true
  service:
    port: 3000
  ingress:
   enabled: true
   hosts:
      - grafana.zapisywarka.local


prometheus:
  enabled: true
  server:
    persistentValume:
      enabled: false
  alertmanager:
    persistentVolume:
      enabled: false

