namePrefix: dev-zapisywarka-

commonLabels: 
  app: zapisywarka-web

configMapGenerator:
  - name: web-configuration
    files:
      - config.json
  - name: ngnix-configuration
    files:
      - nginx.conf


resources:
  - deployment.yml
  - service.yml
  - ingress.yml
  