name: Commit-Stage

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches: ["main"]
defaults:
  run:
    working-directory: src

jobs:  

  build-web:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:         
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 14.18.1
          cache: 'npm'               
      - name: Install dependencies        
        run: npm install    
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2    
      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"
      - name: lint
        run:  npx nx run-many --target=lint --exlude=-api-catalog-catalog,-api-catalog-catalog-test,api-catalog-catalog-api,api-common-infrastructure,api-common-infrastructure-test, api-identity-identity-api, api-identity-identity-core, api-identity-identity-core-test, db-migrations, zapisywarka-api, zapisywarka-api-test
      - name: test
        run:  npx nx npx nx run-many --target=test --exlude=-api-catalog-catalog,-api-catalog-catalog-test,api-catalog-catalog-api,api-common-infrastructure,api-common-infrastructure-test, api-identity-identity-api, api-identity-identity-core, api-identity-identity-core-test, db-migrations, zapisywarka-api, zapisywarka-api-test
      - name: build
        run:  npx nx affected npx nx run-many --target=build --exlude=-api-catalog-catalog,-api-catalog-catalog-test,api-catalog-catalog-api,api-common-infrastructure,api-common-infrastructure-test, api-identity-identity-api, api-identity-identity-core, api-identity-identity-core-test, db-migrations, zapisywarka-api, zapisywarka-api-test
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@f3364599c6aa293cdc2b8391b1b56d0c30e45c8a
        uses: docker/login-action@v1.8.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: ghcr.io
          # Username used to log against the Docker registry
          username: ${{ github.repository_owner }}
          # Password or personal access token used to log against the Docker registry
          password:
            ${{ secrets.GITHUB_TOKEN }}
            # Log out from the Docker registry at the end of a job   
  
      - name: Save build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dotnet-build-assemblies
          path: src/Zapisywarka.API/build/

  