name: Commit-Stage

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches: ["main"]

jobs:
  check-affected:
    runs-on: ubuntu-latest
    outputs:
      affacted: ${{ steps.checkForAffected.outputs.affected }}
    steps:
      - uses: actions/checkout@v2        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:         
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 14.18.1                
      - name: Install dependencies
        working-directory: ./src
        run: npm install  
      - name: Check for Affected Apps
        uses: dkhunt27/action-nx-affected-list@v3
        id: checkForAffected

  build-web:
    runs-on: ubuntu-latest
    needs: check-affected
    if: contains(needs.check-affected.outputs.affacted, 'zapisywarka-rejestracja')
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:         
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 14.18.1                
      - name: Install dependencies
        working-directory: ./src/Zapisywarka.WEB
        run: npm install    
      - name: lint
        run:  npx nx affected --target=lint
      - name: test
        run:  npx nx affected --target=test
      - name: build
        run:  npx nx affected --target=build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@f3364599c6aa293cdc2b8391b1b56d0c30e45c8a
        uses: docker/login-action@v1.8.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: ghcr.io
          # Username used to log against the Docker registry
          username: ${{ github.repository_owner }}
          # Password or personal access token used to log against the Docker registry
          password:
            ${{ secrets.GITHUB_TOKEN }}
            # Log out from the Docker registry at the end of a job

      

      - name: Lint, Test, Deploy
        uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: lint, test, docker
          affacted: true,
          args: --configuration=production
      #todo save test results

      - name: Save build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dotnet-build-assemblies
          path: src/Zapisywarka.API/build/

  