# This is a basic workflow that is manually triggered
name: Deploy with docker-compose

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    
    - name: copy docker compose
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE }}
        passphrase: ${{ secrets.PASSPHRASE }}       
        source: "docker-compose.prod.yml"
        target: "/var/www/zapisywarka"
    
    
    # Runs a single command using the runners shell
    - name: docker-compose up
      uses: appleboy/ssh-action@master
      env: 
        GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
        USERNAME: ${{ secrets.USERNAME }}
        SUDO_PASSWORD: ${{ secrets.PASSWORD }}
      with:
       host: ${{ secrets.HOST }}
       username: ${{ secrets.USERNAME }}
       key: ${{ secrets.SSH_PRIVATE }}
       passphrase: ${{ secrets.PASSPHRASE }}
       envs: GITHUB_TOKEN, USERNAME, SUDO_PASSWORD
       script: | 
         cd /var/www/zapisywarka
         echo $GITHUB_TOKEN | docker login ghcr.io -u msz13 --password-stdin
         echo $SUDO_PASSWORD | sudo -S docker-compose -f docker-compose.prod.yml up -d
         
         
         
       
