name: Zapisywarka Deployment

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

   

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: image



jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
 # test:
 #   runs-on: ubuntu-latest

 #   steps:
 #     - uses: actions/checkout@v2

 #     - name: Run tests
 #       run: |
 #         if [ -f docker-compose.test.yml ]; then
 #           docker-compose --file docker-compose.test.yml build
#            docker-compose --file docker-compose.test.yml run sut
#          else
#            docker build . --file Dockerfile
#          fi

  build-angular-app:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:         
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 12.16.2
      - name: Install dependencies
        working-directory: ./src/Zapisywarka.WEB
        run: npm install
      - name: Build angular app
        working-directory: ./src/Zapisywarka.WEB
        run: npm run nx build zapisywarka-back-office --prod --aot --baseHref=/test/      
          
      - name: Build and push Docker images
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@9379083e426e2e84abb80c8c091f5cdeb7d3fd7a
        uses: docker/build-push-action@v2.3.0
        with:
          # Build's context is the set of files located in the specified PATH or URL
          context: .
          # Path to the Dockerfile
          file: ./Deployment/nginx/Dockerfile
          # List of tags
          tags: |
            zapisywarka-web
          # List of metadata for an image
          labels: latest
     
       
          
    
