name: Test action

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches: ["main"]

defaults:
  run:
    working-directory: src
   
jobs: 

  check-affected:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:         
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 14.18.1
          cache: 'npm' 
      - name: install deps
        run: npm i npx
      - name: check-affected
        run: |
          npx nx graph --focus=zapisywarka-rejestracja --file=output.json
          npx nx print-affected --head=main --base=HEAD~1  | jq --argfile graph ./output.json '.projects | map(select(. as $project | $graph.graph.nodes | has($project))) '
          
